---
- name: Add ansible fact
  hosts: all
  become: true
  gather_facts: false

  tasks:
    - name: Create /etc/ansible/facts.d
      file:
        path: /etc/ansible/facts.d
        state: directory
        recurse: yes
    
    - name: Copy the content to the file
      copy:
        content: "[application]\nname=haproxy\n"
        dest: /etc/ansible/facts.d/environment.fact
