---
- name: Work with ansible facts
  hosts: all
  become: true
  gather_facts: true

  tasks:
    - name: Create facts.d directory
      file:
        path: /etc/ansible/facts.d
        state: directory
        recurse: yes

    - name: Copy the content of the file
      copy:
        content: "[sample_exam]\nserver_role=mysql\n"
        dest: /etc/ansible/facts.d/custom.fact

    - name: Debug
      debug:
        msg: "{{ ansible_local.custom.sample_exam }}"
