---
- name: Running two tasks
  hosts: localhost

  tasks:
    - name: Ping localhost
      ansible.builtin.ping:

    - name: Print Hello World
      ansible.builtin.debug:
        msg: "Hello World"
