---
- name: at and cronjob
  hosts: all
  become: true
  gather_facts: false
  tasks:
    - name: Schedule vmstat execution
      at:
        command: "/usr/bin/vmstat 1>/var/log/vmstat.log; chown automation:automation /var/log/vmstat.log"
        count: 1
        units: minutes
        unique: true

    - name: Schedule an hourly job
      cron:
        name: Dump plugged devices
        minute: "*"
        hour: "*"
        day: "*"
        month: "*"
        job: 'echo ----- $(date "+\%m/\%d/\%y \%H:\%M") >> /var/log/devices.log; /usr/bin/lsblk >> /var/log/devices.log; chown root:root /var/log/devices.log'
