---
- name: Configure system
  hosts: all
  become: true
  gather_facts: true
  vars:
    ram_mb: 1024

  tasks:
    - name: If server has less than 1024MB of RAM
      fail:
        msg: Server should have at least {{ ram_mb }}MB of RAM.
      when: ansible_memtotal_mb <= ram_mb
    - name: Configure swappiness
      sysctl:
        name: vm.swappiness
        value: "10"
        sysctl_set: true
        reload: true
