---
- name: Add yum repository
  hosts: all
  become: true
  gather_facts: false

  tasks:
    - name: Import GPG key
      rpm_key:
        state: present
        key: https://repo.mysql.com/RPM-GPG-KEY-mysql

    - name: Add mysql repo
      yum_repository:
        name: mysql57-community
        description: "MySQL 5.7 Community Server"
        baseurl: http://repo.mysql.com/yum/mysql-5.7-community/el/6/$basearch
        gpgcheck: true
        gpgkey: https://repo.mysql.com/RPM-GPG-KEY-mysql
        enabled: true
